#pragma once

namespace XCom
{

enum ImageType
{
	IMAGE_RANK_ROOKIE,
	IMAGE_RANK_SQUADDIE,
	IMAGE_RANK_SERGEANT,
	IMAGE_RANK_CAPTAIN,
	IMAGE_RANK_COLONEL,
	IMAGE_RANK_COMMANDER,
	IMAGE_BATTLESCAPE_TEST_CORNER,
	IMAGE_BATTLESCAPE_TEST_FLOOR,
	IMAGE_BATTLESCAPE_TEST_FLOOR_1,
	IMAGE_BATTLESCAPE_TEST_FLOOR_2,
	IMAGE_BATTLESCAPE_TEST_LEFT,
	IMAGE_BATTLESCAPE_TEST_TOP,
	IMAGE_BATTLESCAPE_TEST_TOP_WINDOW,
	IMAGE_COUNT				//not an image, just the count of total images
};

}
